- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose
    - git

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Copy docker-compose file to server
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Start containers with docker-compose
  command: docker-compose -f /home/ubuntu/docker-compose.yml up -d
