name: CI - Build and Push to Docker Hub

on:
  push:
    branches: ["feature/actions"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mern-backend
          IMAGE_TAG=${GITHUB_SHA}

          docker build -t $IMAGE_NAME:$IMAGE_TAG ./backend
          docker push $IMAGE_NAME:$IMAGE_TAG

          # Also push latest for convenience
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

####################### THE END ############################################