- name: Restart Postgres
  docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    state: started
    restart: yes
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    ports:
      - "{{ postgres_port }}:5432"
    volumes:
      - "{{ postgres_data_path }}:/var/lib/postgresql/data"
      - "/opt/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - name: "{{ docker_network }}"