- name: Ensure postgres directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - "/opt/postgres"
    - "{{ postgres_data_path }}"

- name: Deploy Postgres conf
  template:
    src: postgresql.conf.j2
    dest: /opt/postgres/postgresql.conf
  notify: Restart Postgres

- name: Run Postgres container
  docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    state: started
    restart_policy: always
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    ports:
      - "{{ postgres_port }}:5432"
    volumes:
      - "{{ postgres_data_path }}:/var/lib/postgresql/data"
      - "/opt/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - name: "{{ docker_network }}"
      