- name: Restart Nuxeo
  docker_container:
    name: "{{ nuxeo_container_name }}"
    image: "{{ nuxeo_image }}"
    state: started
    restart: yes
    ports:
      - "{{ nuxeo_port }}:8080"
    volumes:
      - "{{ nuxeo_conf_path }}:/opt/nuxeo/server/config/nuxeo.conf"
    networks:
      - name: "{{ docker_network }}"
    restart_policy: always
  