- name: Ensure Nuxeo directory exists
  file:
    path: "/opt/nuxeo"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Deploy Nuxeo conf
  template:
    src: nuxeo.conf.j2
    dest: "{{ nuxeo_conf_path }}"
  notify: Restart Nuxeo

- name: Run Nuxeo container
  docker_container:
    name: "{{ nuxeo_container_name }}"
    image: "{{ nuxeo_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ nuxeo_port }}:8080"
    volumes:
      - "{{ nuxeo_conf_path }}:/opt/nuxeo/server/config/nuxeo.conf"
    networks:
      - name: "{{ docker_network }}"
    recreate: yes
