name: Build and Push Docker Images

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - feature/actions

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2 Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3 Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4 Build backend Docker image
      - name: Build backend image
        run: |
          docker build -t sudarshan101/my-docker-backend:latest .

      # 5 Build frontend Docker image
      - name: Build frontend image
        run: |
          docker build -f frontend/Dockerfile -t sudarshan101/my-docker-frontend:latest ./frontend

      # 6 Push backend image
      - name: Push backend image
        run: |
          docker push sudarshan101/my-docker-backend:latest

      # 7 Push frontend image
      - name: Push frontend image
        run: |
          docker push sudarshan101/my-docker-frontend:latest
