- name : Install Docker and pip
  apt:
    name:
      - docker.io
      - python3-pip
    state: present
    update_cache: yes

- name: Install Python Docker SDK from apt
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: yes
    
- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Docker network
  community.docker.docker_network:
    name: "nuxeo_net"
    state: present  
