  - name: Java Installation Playbook
    hosts: all
    become: yes
    # roles:
    #   - java
    tasks:
      - name: Run Java role safely
        block:
          - name: Include Java role
            include_role:
              name: java
        rescue:
          - name: Handle failure if Java role fails
            debug:
              msg: "Java installation failed! Please check the role tasks."
        always:
          - name: Final message
            debug:
              msg: "Java installation block has finished (success or fail)."
