- name: nuxeo-package Installation Playbook
  hosts: all
  become: yes
  collections: community.docker
  gather_facts: no
  tasks:
      - name: Run docker role safely
        block:
          - name: Include docker role
            include_role:
              name: Docker
        rescue:
          - name: Handle failure if Dockerrole fails
            debug:
              msg: "Docker installation failed."
      - name: Run nuxeo-package role safely
        block:
          - name: Include nuxeo-package role
            include_role:
              name: nuxeo-EC2
        rescue:
          - name: Handle failure if nuxeo-package role fails
            debug:
              msg: "nuxeo-package installation failed."
              
      - name: Run nuxeo-package role safely
        block:
          - name: Include postgres-package role
            include_role:
              name: postgres
        rescue:
          - name: Handle failure if postgres-package role fails
            debug:
              msg: "postgres-package installation failed."

          - name: Remove nuxeo container if exists
            community.docker.docker_container:
              name: "{{ nuxeo_container_name }}"
              state: absent
            ignore_errors: true

        always:
          - name: Final message
            debug:
              msg: "nuxeo-package installation block has finished (success or fail)."