- name: 
  hosts: all
  gather_facts: false
  # vars:
  #   install_dir: "/home/ncs/sudarshan"
  #   timezone: "Europe/London"
  tasks:
      - name: Run Java role safely
        block:
          - name: Include Java role
            include_role:
              name: java
        rescue:
          - name: Handle failure if Java role fails
            debug:
              msg: "Java installation failed! Please check the role tasks."
        always:
          - name: Variable Priority
            debug:
              msg: "Install Dir: {{ install_dir }}, Timezone: {{ timezone }}"
            # vars:
            #   install_dir: "/home/ncs/sudarshan"
            #   timezone: "Europe/London"

# The variable precedence order from highest to lowest is:
# 7. Playbook extra vars (always highest precedence, can be set with -e on command line)
# 6. Playbook play vars (defined in vars section)
# 5. Inventory host_vars/server1.yml
# 4. group_vars/webservers.yml
# 3. group_vars/all.yml
# 2. Role vars/main.yml
# 1. Role defaults/main.yml (always lowest precedence)






