version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: icinema-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: icinema-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/iCinema
      PORT: 5000
      SECRET_OR_KEY: your-secret
    command: npm start

  frontend:
    build:
      context: ./frontend
    container_name: icinema-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
