- name: Pulling nuxeo Docker image
  community.docker.docker_image:
    name: "{{ nuxeo_docker_image }}"
    source: pull
    # tag: "{{ nuxeo_docker_image_tag }}"
    force_source: yes
  register: nuxeo_image
  
- name: Ensure old Nuxeo container is removed
  community.docker.docker_container:
    name: "{{ nuxeo_docker_container_name }}"
    state: absent
    force_kill: yes
  
- name: Create nuxeo container
  community.docker.docker_container:
    name: "{{ nuxeo_docker_container_name }}"
    image: "{{ nuxeo_docker_image }}"
    state: started
    # restart_policy: always
    ports:
      - "8080:8080"
    

