name: Build and Push Docker Images

on:
  push:
    branches:
      - feature/workflow
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2 Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3 Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4 Build backend Docker image
      - name: Build backend image
        run: |
          docker build -t sudarshan101/my-docker-backend:latest . 2>&1 | tee logs/backend_build.log

      # 5 Build frontend Docker image (corrected path)
      - name: Build frontend image
        run: |
          docker build -f iCinema/frontend/Dockerfile \
            -t sudarshan101/my-docker-frontend:latest ./iCinema/frontend  2>&1 | tee logs/frontend_build.log

      # 6 Push backend image
      - name: Push backend image
        run: |
          docker push sudarshan101/my-docker-backend:latest 
          
          # Capture last 50 lines for SNS notification
          tail -n 50 logs/backend_build.log > logs/backend_snippet.log

      # 7 Push frontend image
      - name: Push frontend image
        run: |
          docker push sudarshan101/my-docker-frontend:latest
      
          # Capture last 50 lines for SNS notification
          tail -n 50 logs/backend_build.log > logs/frontend_snippet.log

      # 8 Publish error snippet to SNS (only if step fails)
      - name: Notify via SNS on failure
        if: failure()  # runs only if previous step fails
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          ERROR_LOG=$(cat logs/backend_snippet.log)
          aws sns publish \
            --region "$AWS_REGION" \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "GitHub Actions: Backend Build Failed" \
            --message "$ERROR_LOG"
      
       # 9 Publish error snippet to SNS (only if step fails)
      - name: Notify via SNS on failure
        if: failure()  # runs only if previous step fails
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          ERROR_LOG=$(cat logs/frontend_snippet.log)
          aws sns publish \
            --region "$AWS_REGION" \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "GitHub Actions: Frontend Build Failed" \
            --message "$ERROR_LOG"
