name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible-core

      # Save private key from GitHub secret
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Create dynamic inventory
        run: |
          echo "[icinema-server]" > iCinema/ansible/inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=private_key.pem" >> iCinema/ansible/inventory.ini


      - name: Run Ansible playbook
        run: |
          ansible-playbook -i iCinema/ansible/inventory.ini iCinema/ansible/playbook.yml
